name: aws_practice
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  amplify_api: ^0.4.0
  amplify_core: ^0.4.0
  amplify_flutter: ^0.4.0
  amplify_datastore: ^0.4.0
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.6.1
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true